apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: emdeekaa-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/emdeekaa/k3s-emdeekaa-prod.git
    path: charts/ingress-nginx/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: emdeekaa-ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
