apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emdeekaa-root-app
  namespace: emdeekaa-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.prd.emdeekaa.com/src/k3s-emdeekaa-prod.git
    path: charts/root-app/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: emdeekaa-argocd
  syncPolicy:
    automated:
      selfHeal: true
