apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # https://acme-v02.api.letsencrypt.org/directory)  https://acme-staging-v02.api.letsencrypt.org/directory 
    email: mdk@emdeekaa.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx