argo-cd:
  configs:
    cm:
      admin.enabled: true
      policy.csv: |
        g, ArgoCD Admins, role:admin
        g, ArgoCD Viewers, role:readonly
  global:
    domain: argo.k3s.emdeekaa.com
  dex:
    enabled: true
    config: |
      connectors:
      - config:
              issuer: https://authentik.emdeekaa.com/application/o/argocd/
              clientID: P0Zh3mwk1JmdiMnhwwXtpuLOADzJ2puylloMJwUg
              clientSecret: 9H228uMz55bCvU3oSAQZ8xsjXlHrOP8v3eKvPMoivt6JHcobA8JnZHWBCI5ARzrml2AwG8onJPNYQeB7RAnpRTpjWufMjANcb4qayKpfJYX9VVaGurs8YhdVj6tEsYrI
              insecureEnableGroups: false
              scopes:
                - openid
                - profile
                - email
            name: authentik
            type: oidc
            id: authentik
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    oidcConfig:
      name: authentik
      clientID: P0Zh3mwk1JmdiMnhwwXtpuLOADzJ2puylloMJwUg
      issuer: https://authentik.emdeekaa.com/application/o/argocd/
      clientSecret: 9H228uMz55bCvU3oSAQZ8xsjXlHrOP8v3eKvPMoivt6JHcobA8JnZHWBCI5ARzrml2AwG8onJPNYQeB7RAnpRTpjWufMjANcb4qayKpfJYX9VVaGurs8YhdVj6tEsYrI
      requestedScopes: ["openid", "profile", "email", "groups"]
      redirectURI: https://argo.k3s.emdeekaa.com/argocd/callback
      logoutURL: https://authentik.emdeekaa.com/logout
