argo-cd:
  global:
    domain: argo.k3s.emdeekaa.com
  oidc:
    enabled: true
    issuer: https://authentik.emdeekaa.com/application/o/argocd/
    clientId: "P0Zh3mwk1JmdiMnhwwXtpuLOADzJ2puylloMJwUg"
    clientSecret: "9H228uMz55bCvU3oSAQZ8xsjXlHrOP8v3eKvPMoivt6JHcobA8JnZHWBCI5ARzrml2AwG8onJPNYQeB7RAnpRTpjWufMjANcb4qayKpfJYX9VVaGurs8YhdVj6tEsYrI"
    insecureEnableGroups: true
  configs:
    cm:
      admin.enabled: true
      policy.csv: |
        g, ArgoCD Admins, role:admin
        g, ArgoCD Viewers, role:readonly
  