argo-cd:
  global:
    domain: argo.k3s.emdeekaa.com

  oidc:
    enabled: true
    issuer: https://authentik.emdeekaa.com/application/o/argocd/
    clientId: "P0Zh3mwk1JmdiMnhwwXtpuLOADzJ2puylloMJwUg"
    clientSecret: "9H228uMz55bCvU3oSAQZ8xsjXlHrOP8v3eKvPMoivt6JHcobA8JnZHWBCI5ARzrml2AwG8onJPNYQeB7RAnpRTpjWufMjANcb4qayKpfJYX9VVaGurs8YhdVj6tEsYrI"
    insecureEnableGroups: true

  configs:
    secret:
      extra:
        dex.authentik.clientSecret: "9H228uMz55bCvU3oSAQZ8xsjXlHrOP8v3eKvPMoivt6JHcobA8JnZHWBCI5ARzrml2AwG8onJPNYQeB7RAnpRTpjWufMjANcb4qayKpfJYX9VVaGurs8YhdVj6tEsYrI"
    cm:
      url: https://argo.k3s.emdeekaa.com
      dex.config: |
          connectors:
          - config:
              issuer: https://authentik.emdeekaa.com/application/o/argocd/
              clientID: P0Zh3mwk1JmdiMnhwwXtpuLOADzJ2puylloMJwUg
              clientSecret: 9H228uMz55bCvU3oSAQZ8xsjXlHrOP8v3eKvPMoivt6JHcobA8JnZHWBCI5ARzrml2AwG8onJPNYQeB7RAnpRTpjWufMjANcb4qayKpfJYX9VVaGurs8YhdVj6tEsYrI
              insecureEnableGroups: true
              scopes:
                - openid
                - profile
                - email
                - groups
            name: authentik
            type: oidc
            id: authentik
      create: true
      admin.enabled: true

  rbac:
    policy.csv: |
      p, role:readonly, applications, get, */*, allow
      p, role:readonly, repositories, get, */*, allow
      p, role:readonly, clusters, get, */*, allow
      p, role:admin, *, *, */*, allow
      g, ArgoCD Admins, role:admin
      g, ArgoCD Viewers, role:readonly
    scopes: '[groups]'