argo-cd:
  global:
    domain: argo.k3s.emdeekaa.com

  rbac:
    create: true
    policy.csv: |
      p, role:admin, applications, *, *, allow
      p, role:admin, clusters, *, *, allow
      p, role:admin, repositories, *, *, allow
      p, role:admin, certificates, *, *, allow
      p, role:admin, projects, *, *, allow
      p, role:admin, accounts, *, *, allow
      p, role:admin, gpgkeys, *, *, allow
      p, role:admin, logs, *, *, allow
      p, role:admin, configmaps, *, *, allow
      p, role:admin, secrets, *, *, allow
      p, role:admin, serviceaccounts, *, *, allow
      p, role:admin, events, *, *, allow
      p, role:admin, metrics, *, *, allow
      g, ArgoCD Admins, role:admin
      g, ArgoCD Viewers, role:readonly
    scopes: "[groups]"
    policy.matchMode: "glob"

  oidc:
    enabled: true
    issuer: https://authentik.emdeekaa.com/application/o/argocd/
    clientId: "P0Zh3mwk1JmdiMnhwwXtpuLOADzJ2puylloMJwUg"
    clientSecret: "9H228uMz55bCvU3oSAQZ8xsjXlHrOP8v3eKvPMoivt6JHcobA8JnZHWBCI5ARzrml2AwG8onJPNYQeB7RAnpRTpjWufMjANcb4qayKpfJYX9VVaGurs8YhdVj6tEsYrI"
    insecureEnableGroups: true

  configs:
    secret:
      extra:
        dex.authentik.clientSecret: "9H228uMz55bCvU3oSAQZ8xsjXlHrOP8v3eKvPMoivt6JHcobA8JnZHWBCI5ARzrml2AwG8onJPNYQeB7RAnpRTpjWufMjANcb4qayKpfJYX9VVaGurs8YhdVj6tEsYrI"
    cm:
      url: https://argo.k3s.emdeekaa.com
      dex.config: |
          connectors:
          - config:
              issuer: https://authentik.emdeekaa.com/application/o/argocd/
              clientID: P0Zh3mwk1JmdiMnhwwXtpuLOADzJ2puylloMJwUg
              clientSecret: 9H228uMz55bCvU3oSAQZ8xsjXlHrOP8v3eKvPMoivt6JHcobA8JnZHWBCI5ARzrml2AwG8onJPNYQeB7RAnpRTpjWufMjANcb4qayKpfJYX9VVaGurs8YhdVj6tEsYrI
              insecureEnableGroups: true
              scopes:
                - openid
                - profile
                - email
                - groups
            name: authentik
            type: oidc
            id: authentik
      create: true
      admin.enabled: true