apiVersion: v2
name: cert-manager
version: 1.0.0
dependencies:
  - name: cert-manager
    version: 1.3.7
    repository: https://charts.bitnami.com/bitnami


# https://github.com/kubernetes/ingress-nginx
