apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-k3s-emdeekaa-com
  namespace: emdeekaa-argocd
spec:
  commonName: argo.k3s.emdeekaa.com
  secretName: argo-k3s-emdeekaa-com-secret
  dnsNames:
    - argo.k3s.emdeekaa.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
